import '../models/bug_color.dart';
import '../models/level_definition.dart';
import '../models/objective.dart';
import '../models/power_up.dart';

const _lockedSlots = <LevelPowerSlot>[
  LevelPowerSlot(locked: true),
  LevelPowerSlot(locked: true),
  LevelPowerSlot(locked: true),
];

const _berryLocked = <LevelPowerSlot>[
  LevelPowerSlot(type: PowerUpType.berry, count: 1),
  LevelPowerSlot(locked: true),
  LevelPowerSlot(locked: true),
];

final demoLevels = <LevelDefinition>[
  LevelDefinition(
    id: 'tutorial_drag_glow',
    name: 'Drag to Glow',
    startColumn: 2,
    scoreTarget: 100,
    pressureEnabled: false,
    minimumBugCount: 0,
    powerSlots: _lockedSlots,
    tutorialText: 'Drag matching bottom bugs together.',
    columns: [
      [BugColor.red],
      [BugColor.blue, BugColor.red],
      [BugColor.yellow, BugColor.red],
      [BugColor.purple],
      [BugColor.orange],
      [],
    ],
    objective: Objective.clearTotal(2),
  ),
  LevelDefinition(
    id: 'tutorial_pressure_clear',
    name: 'First Pressure',
    startColumn: 1,
    scoreTarget: 180,
    pressureEnabled: true,
    refillIntervalSeconds: 11,
    minimumBugCount: 8,
    powerSlots: _lockedSlots,
    tutorialText: 'Make glowing bugs before pressure fills the board.',
    columns: [
      [BugColor.blue, BugColor.red],
      [BugColor.yellow, BugColor.blue],
      [BugColor.orange, BugColor.blue],
      [BugColor.red, BugColor.purple],
      [BugColor.purple],
      [],
    ],
    objective: Objective.clearTotal(4),
  ),
  LevelDefinition(
    id: 'unlock_berry',
    name: 'Berry Unlock',
    startColumn: 3,
    scoreTarget: 160,
    pressureEnabled: true,
    refillIntervalSeconds: 10.5,
    minimumBugCount: 9,
    powerSlots: _berryLocked,
    tutorialText: 'Berry clears a column for space, but gives no score.',
    columns: [
      [BugColor.purple, BugColor.red, BugColor.yellow],
      [BugColor.orange, BugColor.blue],
      [BugColor.red, BugColor.purple],
      [BugColor.yellow, BugColor.orange, BugColor.blue],
      [BugColor.purple, BugColor.red],
      [],
    ],
    objective: Objective.clearTotal(4),
  ),
  LevelDefinition(
    id: 'berry_practice',
    name: 'Berry Practice',
    startColumn: 2,
    scoreTarget: 220,
    pressureEnabled: true,
    refillIntervalSeconds: 10,
    minimumBugCount: 10,
    powerSlots: const [
      LevelPowerSlot(type: PowerUpType.berry, count: 3),
      LevelPowerSlot(locked: true),
      LevelPowerSlot(locked: true),
    ],
    tutorialText: 'Use free Berries to open space, then score with clears.',
    columns: [
      [BugColor.red, BugColor.orange, BugColor.purple],
      [BugColor.blue, BugColor.yellow, BugColor.orange],
      [BugColor.orange, BugColor.red],
      [BugColor.yellow, BugColor.blue, BugColor.red],
      [BugColor.purple, BugColor.yellow],
      [BugColor.blue],
    ],
    objective: Objective.clearTotal(5),
  ),
  LevelDefinition(
    id: 'bloom_setup',
    name: 'Bloom Setup',
    startColumn: 0,
    scoreTarget: 240,
    pressureEnabled: true,
    refillIntervalSeconds: 9.5,
    minimumBugCount: 11,
    powerSlots: const [
      LevelPowerSlot(type: PowerUpType.bloom, count: 2),
      LevelPowerSlot(locked: true),
      LevelPowerSlot(locked: true),
    ],
    tutorialText: 'Bloom recolors a row so your next move can score.',
    columns: [
      [BugColor.red, BugColor.blue],
      [BugColor.orange, BugColor.yellow],
      [BugColor.purple, BugColor.blue],
      [BugColor.yellow, BugColor.red],
      [BugColor.orange, BugColor.purple],
      [BugColor.red],
    ],
    objective: Objective.clearColor(BugColor.blue, 4),
  ),
  LevelDefinition(
    id: 'big_bug_intro',
    name: 'BIG Bug Intro',
    startColumn: 4,
    scoreTarget: 320,
    pressureEnabled: true,
    refillIntervalSeconds: 9.25,
    minimumBugCount: 12,
    powerSlots: _berryLocked,
    tutorialText: 'Four matching bugs make a BIG bug. Clear it with glow.',
    columns: [
      [BugColor.orange, BugColor.orange],
      [BugColor.orange, BugColor.orange],
      [BugColor.blue, BugColor.red],
      [BugColor.yellow, BugColor.blue],
      [BugColor.red, BugColor.purple],
      [BugColor.purple],
    ],
    objective: Objective.clearTotal(6),
  ),
  LevelDefinition(
    id: 'second_slot',
    name: 'Second Slot',
    startColumn: 2,
    scoreTarget: 360,
    pressureEnabled: true,
    refillIntervalSeconds: 8.75,
    minimumBugCount: 13,
    powerSlots: const [
      LevelPowerSlot(type: PowerUpType.berry, count: 2),
      LevelPowerSlot(type: PowerUpType.bloom, count: 1),
      LevelPowerSlot(locked: true),
    ],
    tutorialText: 'Second slot unlocked: combine space clears and setup.',
    columns: [
      [BugColor.blue, BugColor.red, BugColor.yellow],
      [BugColor.yellow, BugColor.blue],
      [BugColor.red, BugColor.orange],
      [BugColor.purple, BugColor.orange, BugColor.red],
      [BugColor.blue, BugColor.purple],
      [BugColor.yellow],
    ],
    objective: Objective.clearTotal(7),
  ),
  LevelDefinition(
    id: 'pollen_intro',
    name: 'Pollen Burst',
    startColumn: 1,
    scoreTarget: 420,
    pressureEnabled: true,
    refillIntervalSeconds: 8.5,
    minimumBugCount: 14,
    powerSlots: const [
      LevelPowerSlot(type: PowerUpType.berry, count: 1),
      LevelPowerSlot(type: PowerUpType.pollen, count: 2),
      LevelPowerSlot(locked: true),
    ],
    tutorialText: 'Pollen scores by clearing a 3x3 patch anywhere.',
    columns: [
      [BugColor.red, BugColor.yellow, BugColor.blue],
      [BugColor.orange, BugColor.purple, BugColor.blue],
      [BugColor.yellow, BugColor.red, BugColor.orange],
      [BugColor.blue, BugColor.orange],
      [BugColor.purple, BugColor.red],
      [BugColor.yellow],
    ],
    objective: Objective.clearTotal(8),
  ),
  LevelDefinition(
    id: 'combo_bridge',
    name: 'Combo Bridge',
    startColumn: 3,
    scoreTarget: 520,
    pressureEnabled: true,
    refillIntervalSeconds: 8,
    minimumBugCount: 15,
    powerSlots: const [
      LevelPowerSlot(type: PowerUpType.berry, count: 1),
      LevelPowerSlot(type: PowerUpType.bloom, count: 1),
      LevelPowerSlot(locked: true),
    ],
    tutorialText: 'Use Bloom to build a chain, then detonate with glow.',
    columns: [
      [BugColor.purple, BugColor.red, BugColor.blue],
      [BugColor.blue, BugColor.orange, BugColor.red],
      [BugColor.red, BugColor.yellow],
      [BugColor.orange, BugColor.blue, BugColor.purple],
      [BugColor.yellow, BugColor.purple],
      [BugColor.red, BugColor.yellow],
    ],
    objective: Objective.reachCascade(2),
  ),
  LevelDefinition(
    id: 'water_intro',
    name: 'Water Drop',
    startColumn: 2,
    scoreTarget: 620,
    pressureEnabled: true,
    refillIntervalSeconds: 7.5,
    minimumBugCount: 16,
    powerSlots: const [
      LevelPowerSlot(type: PowerUpType.berry, count: 1),
      LevelPowerSlot(type: PowerUpType.pollen, count: 1),
      LevelPowerSlot(type: PowerUpType.water, count: 1),
    ],
    tutorialText: 'Third slot unlocked: Water Drop scores by color.',
    columns: [
      [BugColor.blue, BugColor.red, BugColor.orange],
      [BugColor.red, BugColor.blue, BugColor.yellow],
      [BugColor.yellow, BugColor.purple, BugColor.red],
      [BugColor.orange, BugColor.red, BugColor.blue],
      [BugColor.purple, BugColor.yellow, BugColor.orange],
      [BugColor.blue, BugColor.purple],
    ],
    objective: Objective.clearColor(BugColor.red, 6),
  ),
  LevelDefinition(
    id: 'firefly_preview',
    name: 'Firefly Preview',
    startColumn: 3,
    scoreTarget: 760,
    pressureEnabled: true,
    refillIntervalSeconds: 7,
    minimumBugCount: 18,
    powerSlots: const [
      LevelPowerSlot(type: PowerUpType.pollen, count: 1),
      LevelPowerSlot(type: PowerUpType.water, count: 1),
      LevelPowerSlot(type: PowerUpType.firefly, count: 1),
    ],
    tutorialText: 'Firefly is rare: it clears half the small bugs.',
    columns: [
      [BugColor.red, BugColor.orange, BugColor.blue],
      [BugColor.blue, BugColor.yellow, BugColor.purple],
      [BugColor.orange, BugColor.purple, BugColor.red],
      [BugColor.yellow, BugColor.red, BugColor.blue],
      [BugColor.purple, BugColor.blue, BugColor.orange],
      [BugColor.red, BugColor.yellow, BugColor.purple],
    ],
    objective: Objective.clearTotal(10),
  ),
];
