// GENERATED CODE - DO NOT MODIFY BY HAND.
// Generated from data/levels/map01.json by tool/generate_levels.dart.

import '../models/bug_color.dart';
import '../models/level_definition.dart';
import '../models/objective.dart';

const _lockedSlots = <LevelPowerSlot>[
  LevelPowerSlot(locked: true),
  LevelPowerSlot(locked: true),
  LevelPowerSlot(locked: true),
];

final map01Levels = <LevelDefinition>[
  LevelDefinition(
    id: 'map01_grove_sorting',
    name: 'Grove Sorting',
    startColumn: 2,
    scoreTarget: 560,
    pressureEnabled: false,
    refillIntervalSeconds: 9,
    minimumBugCount: 0,
    stuckHelpEnabled: true,
    powerSlots: _lockedSlots,
    tutorialText: '',
    columns: [
      [BugColor.red, BugColor.blue, BugColor.yellow],
      [BugColor.blue, BugColor.yellow, BugColor.red],
      [BugColor.yellow, BugColor.red, BugColor.blue],
      [BugColor.yellow, BugColor.red, BugColor.blue],
      [BugColor.blue, BugColor.yellow, BugColor.red],
      [BugColor.red, BugColor.blue, BugColor.yellow],
    ],
    objective: Objective.makeGlow(4),
    objectives: [Objective.makeGlow(4), Objective.clearTotal(16)],
    solverMaxMoves: 20,
    designTags: ['intro', 'glow', 'mirror', 'pattern'],
    starThresholds: const LevelStarThresholds(
      twoStarSecondsRemaining: 60,
      threeStarSecondsRemaining: 90,
    ),
  ),
  LevelDefinition(
    id: 'map01_color_clusters',
    name: 'Color Clusters',
    startColumn: 2,
    scoreTarget: 700,
    pressureEnabled: false,
    refillIntervalSeconds: 9,
    minimumBugCount: 0,
    stuckHelpEnabled: true,
    powerSlots: _lockedSlots,
    tutorialText: '',
    columns: [
      [BugColor.red, BugColor.red, BugColor.blue, BugColor.yellow],
      [BugColor.red, BugColor.blue, BugColor.blue, BugColor.orange],
      [BugColor.blue, BugColor.yellow, BugColor.yellow, BugColor.orange],
      [BugColor.yellow, BugColor.orange, BugColor.yellow, BugColor.blue],
      [BugColor.orange, BugColor.blue, BugColor.blue, BugColor.yellow],
      [BugColor.orange, BugColor.orange, BugColor.red, BugColor.red],
    ],
    objective: Objective.makeGlow(4),
    objectives: [Objective.makeGlow(4), Objective.clearAll()],
    solverMaxMoves: 22,
    designTags: ['clear', 'clusters', 'islands', 'pattern'],
    starThresholds: const LevelStarThresholds(
      twoStarSecondsRemaining: 50,
      threeStarSecondsRemaining: 80,
    ),
  ),
  LevelDefinition(
    id: 'map01_pressure_sprouts',
    name: 'Pressure Sprouts',
    startColumn: 3,
    scoreTarget: 760,
    pressureEnabled: true,
    refillIntervalSeconds: 12,
    minimumBugCount: 14,
    stuckHelpEnabled: true,
    powerSlots: _lockedSlots,
    tutorialText: '',
    columns: [
      [BugColor.red, BugColor.blue, BugColor.yellow],
      [BugColor.yellow, BugColor.red, BugColor.blue],
      [BugColor.blue, BugColor.yellow, BugColor.red],
      [BugColor.red, BugColor.blue, BugColor.yellow],
      [BugColor.yellow, BugColor.red, BugColor.blue],
      [BugColor.blue, BugColor.yellow, BugColor.red],
    ],
    objective: Objective.makeGlow(5),
    objectives: [Objective.makeGlow(5), Objective.clearTotal(22)],
    solverMaxMoves: 24,
    designTags: ['pressure', 'sprouts', 'vertical', 'pattern'],
    starThresholds: const LevelStarThresholds(
      twoStarSecondsRemaining: 45,
      threeStarSecondsRemaining: 78,
    ),
  ),
  LevelDefinition(
    id: 'map01_blue_orchard',
    name: 'Blue Orchard',
    startColumn: 1,
    scoreTarget: 840,
    pressureEnabled: true,
    refillIntervalSeconds: 11.5,
    minimumBugCount: 16,
    stuckHelpEnabled: true,
    powerSlots: _lockedSlots,
    tutorialText: '',
    columns: [
      [BugColor.blue, BugColor.blue, BugColor.yellow, BugColor.blue],
      [BugColor.blue, BugColor.blue, BugColor.red, BugColor.orange],
      [BugColor.blue, BugColor.yellow, BugColor.yellow, BugColor.red],
      [BugColor.orange, BugColor.purple, BugColor.blue, BugColor.blue],
      [BugColor.red, BugColor.blue, BugColor.yellow, BugColor.blue],
      [BugColor.yellow, BugColor.blue, BugColor.orange, BugColor.blue],
    ],
    objective: Objective.clearColor(BugColor.blue, 10),
    objectives: [
      Objective.clearColor(BugColor.blue, 10),
      Objective.clearTotal(22),
    ],
    solverMaxMoves: 24,
    designTags: ['color-focus', 'blue', 'river', 'pattern'],
    starThresholds: const LevelStarThresholds(
      twoStarSecondsRemaining: 42,
      threeStarSecondsRemaining: 75,
    ),
  ),
  LevelDefinition(
    id: 'map01_chain_bridge',
    name: 'Chain Bridge',
    startColumn: 3,
    scoreTarget: 900,
    pressureEnabled: false,
    refillIntervalSeconds: 9,
    minimumBugCount: 0,
    stuckHelpEnabled: true,
    powerSlots: _lockedSlots,
    tutorialText: '',
    columns: [
      [
        BugColor.yellow,
        BugColor.blue,
        BugColor.red,
        BugColor.red,
        BugColor.blue,
        BugColor.yellow,
      ],
      [
        BugColor.purple,
        BugColor.yellow,
        BugColor.red,
        BugColor.blue,
        BugColor.orange,
      ],
      [
        BugColor.orange,
        BugColor.red,
        BugColor.red,
        BugColor.purple,
        BugColor.yellow,
      ],
      [
        BugColor.orange,
        BugColor.yellow,
        BugColor.red,
        BugColor.purple,
        BugColor.blue,
      ],
      [
        BugColor.purple,
        BugColor.yellow,
        BugColor.red,
        BugColor.blue,
        BugColor.orange,
      ],
      [
        BugColor.yellow,
        BugColor.blue,
        BugColor.red,
        BugColor.red,
        BugColor.blue,
        BugColor.yellow,
      ],
    ],
    objective: Objective.reachCascade(2),
    objectives: [Objective.reachCascade(2), Objective.clearTotal(24)],
    solverMaxMoves: 24,
    designTags: ['chain', 'bridge', 'symmetric', 'pattern'],
    starThresholds: const LevelStarThresholds(
      twoStarSecondsRemaining: 38,
      threeStarSecondsRemaining: 70,
    ),
  ),
  LevelDefinition(
    id: 'map01_tall_grass_rush',
    name: 'Tall Grass Rush',
    startColumn: 2,
    scoreTarget: 980,
    pressureEnabled: true,
    refillIntervalSeconds: 10.5,
    minimumBugCount: 18,
    stuckHelpEnabled: true,
    powerSlots: _lockedSlots,
    tutorialText: '',
    columns: [
      [
        BugColor.red,
        BugColor.red,
        BugColor.yellow,
        BugColor.orange,
        BugColor.purple,
      ],
      [
        BugColor.red,
        BugColor.red,
        BugColor.blue,
        BugColor.purple,
        BugColor.orange,
      ],
      [
        BugColor.blue,
        BugColor.yellow,
        BugColor.orange,
        BugColor.purple,
        BugColor.red,
      ],
      [
        BugColor.orange,
        BugColor.purple,
        BugColor.red,
        BugColor.yellow,
        BugColor.blue,
      ],
      [
        BugColor.purple,
        BugColor.red,
        BugColor.yellow,
        BugColor.blue,
        BugColor.orange,
      ],
      [
        BugColor.yellow,
        BugColor.orange,
        BugColor.purple,
        BugColor.red,
        BugColor.blue,
      ],
    ],
    objective: Objective.clearBig(1),
    objectives: [Objective.clearBig(1), Objective.clearTotal(30)],
    solverMaxMoves: 26,
    designTags: ['pressure', 'wave', 'diagonal', 'pattern'],
    starThresholds: const LevelStarThresholds(
      twoStarSecondsRemaining: 32,
      threeStarSecondsRemaining: 65,
    ),
  ),
  LevelDefinition(
    id: 'map01_big_bug_nest',
    name: 'BIG Bug Nest',
    startColumn: 4,
    scoreTarget: 1040,
    pressureEnabled: false,
    refillIntervalSeconds: 9,
    minimumBugCount: 0,
    stuckHelpEnabled: true,
    powerSlots: _lockedSlots,
    tutorialText: '',
    columns: [
      [BugColor.orange, BugColor.orange, BugColor.blue, BugColor.yellow],
      [BugColor.orange, BugColor.orange, BugColor.red, BugColor.yellow],
      [BugColor.blue, BugColor.purple, BugColor.orange, BugColor.red],
      [BugColor.yellow, BugColor.orange, BugColor.blue, BugColor.red],
      [BugColor.red, BugColor.orange, BugColor.yellow, BugColor.purple],
      [BugColor.purple, BugColor.blue, BugColor.yellow, BugColor.orange],
    ],
    objective: Objective.clearBig(1),
    objectives: [
      Objective.clearBig(1),
      Objective.makeGlow(3),
      Objective.clearTotal(20),
    ],
    solverMaxMoves: 24,
    designTags: ['big', 'nest', 'orange', 'pattern'],
    starThresholds: const LevelStarThresholds(
      twoStarSecondsRemaining: 35,
      threeStarSecondsRemaining: 65,
    ),
  ),
  LevelDefinition(
    id: 'map01_twin_paths',
    name: 'Twin Paths',
    startColumn: 3,
    scoreTarget: 1120,
    pressureEnabled: true,
    refillIntervalSeconds: 9.75,
    minimumBugCount: 20,
    stuckHelpEnabled: true,
    powerSlots: _lockedSlots,
    tutorialText: '',
    columns: [
      [
        BugColor.purple,
        BugColor.blue,
        BugColor.yellow,
        BugColor.red,
        BugColor.orange,
      ],
      [
        BugColor.yellow,
        BugColor.purple,
        BugColor.blue,
        BugColor.red,
        BugColor.orange,
      ],
      [
        BugColor.purple,
        BugColor.purple,
        BugColor.red,
        BugColor.yellow,
        BugColor.blue,
      ],
      [
        BugColor.purple,
        BugColor.purple,
        BugColor.red,
        BugColor.yellow,
        BugColor.blue,
      ],
      [
        BugColor.yellow,
        BugColor.purple,
        BugColor.blue,
        BugColor.red,
        BugColor.orange,
      ],
      [
        BugColor.purple,
        BugColor.blue,
        BugColor.yellow,
        BugColor.red,
        BugColor.orange,
      ],
    ],
    objective: Objective.reachCascade(2),
    objectives: [
      Objective.reachCascade(2),
      Objective.clearBig(1),
      Objective.clearColor(BugColor.purple, 10),
    ],
    solverMaxMoves: 28,
    designTags: ['chain', 'purple', 'twin-paths', 'mirror', 'pattern'],
    starThresholds: const LevelStarThresholds(
      twoStarSecondsRemaining: 28,
      threeStarSecondsRemaining: 60,
    ),
  ),
  LevelDefinition(
    id: 'map01_canopy_trial',
    name: 'Canopy Trial',
    startColumn: 3,
    scoreTarget: 1200,
    pressureEnabled: true,
    refillIntervalSeconds: 9.25,
    minimumBugCount: 22,
    stuckHelpEnabled: true,
    powerSlots: _lockedSlots,
    tutorialText: '',
    columns: [
      [
        BugColor.orange,
        BugColor.orange,
        BugColor.blue,
        BugColor.yellow,
        BugColor.purple,
        BugColor.red,
      ],
      [
        BugColor.orange,
        BugColor.orange,
        BugColor.red,
        BugColor.yellow,
        BugColor.blue,
        BugColor.purple,
      ],
      [
        BugColor.blue,
        BugColor.purple,
        BugColor.red,
        BugColor.yellow,
        BugColor.orange,
      ],
      [
        BugColor.yellow,
        BugColor.purple,
        BugColor.red,
        BugColor.blue,
        BugColor.orange,
      ],
      [
        BugColor.red,
        BugColor.orange,
        BugColor.yellow,
        BugColor.purple,
        BugColor.blue,
      ],
      [
        BugColor.purple,
        BugColor.blue,
        BugColor.yellow,
        BugColor.orange,
        BugColor.red,
      ],
    ],
    objective: Objective.clearBig(1),
    objectives: [
      Objective.clearBig(1),
      Objective.makeGlow(4),
      Objective.clearTotal(32),
    ],
    solverMaxMoves: 30,
    designTags: ['pressure', 'big', 'canopy', 'diagonal', 'pattern'],
    starThresholds: const LevelStarThresholds(
      twoStarSecondsRemaining: 20,
      threeStarSecondsRemaining: 50,
    ),
  ),
];
